package gmail.ahmedmeabbas.realestateapp.listings.models

import java.util.*

sealed class Listing {

    data class Apartment(
        val id: String? = null,
        val state: String? = null,
        val city: String? = null,
        val region: String? = null,
        val listerId: String? = null,
        val dateAdded: Date? = null,
        val propertyType: String = PropertyType.APARTMENT,
        val advertiser: String? = null,
        val phoneNumber: Int? = null,
        val email: String? = null,
        val fullAddress: String? = null,
        val area: Double? = null,
        val yearBuilt: Int? = null,
        val finished: Boolean? = null,
        val furnished: Boolean? = null,
        val bedrooms: Int? = null,
        val bathrooms: Int? = null,
        val kitchen: Boolean? = null,
        val livingRoom: Boolean? = null,
        val balcony: Boolean? = null,
        val floorNumber: Int? = null,
        val detailsMoreInfo: String? = null,
        val electricity: Boolean? = null,
        val water: Boolean? = null,
        val elevator: Boolean? = null,
        val parking: Boolean? = null,
        val backupGenerator: Boolean? = null,
        val security: Boolean? = null,
        val utilitiesMoreInfo: String? = null,
        val photoUrls: List<String>? = null,
        val price: Price? = null,
        val monthlyInstallments: Boolean? = null,
        val downPayment: Double? = null,
        val installment: Double? = null,
        val installmentPeriod: Int? = null,
        val longitude: String? = null,
        val latitude: String? = null,
        val additionalInfo: String? = null,
        val priceHistory: List<Price>? = null,
        val listingStatus: String? = null
    )
    data class House(
        val id: String? = null,
        val state: String? = null,
        val city: String? = null,
        val region: String? = null,
        val listerId: String? = null,
        val dateAdded: Date? = null,
        val propertyType: String = PropertyType.HOUSE,
        val advertiser: String? = null,
        val phoneNumber: Int? = null,
        val email: String? = null,
        val fullAddress: String? = null,
        val lotArea: Double? = null,
        val builtArea: Double? = null,
        val yearBuilt: Int? = null,
        val structureType: String? = null,
        val finishing: String? = null,
        val bedrooms: Int? = null,
        val bathrooms: Int? = null,
        val kitchens: Int? = null,
        val halls: Int? = null,
        val floors: Int? = null,
        val basement: Boolean? = null,
        val carGarage: Boolean? = null,
        val numberCars: Int? = null,
        val detailsMoreInfo: String? = null,
        val electricity: Boolean? = null,
        val water: Boolean? = null,
        val utilitiesMoreInfo: String? = null,
        val photoUrls: List<String>? = null,
        val price: Price? = null,
        val monthlyInstallments: Boolean? = null,
        val downPayment: Double? = null,
        val installment: Double? = null,
        val installmentPeriod: Int? = null,
        val additionalInfo: String? = null,
        val longitude: String? = null,
        val latitude: String? = null,
        val priceHistory: List<Price>? = null,
        val listingStatus: String? = null
    )
}

data class Price(
    val dateAdded: Date? = null,
    val currency: String? = null,
    val price: Double? = null
)
